language: julia

os:
  - linux

env:
  - COVERAGE_JULIA_VERSION="1.4"

julia:
  - 1.3
  - 1.4

notifications:
  email: false

script:
  - julia -e 'import Pkg; Pkg.test("Rocket")'
  - |
    if [ $TRAVIS_JULIA_VERSION == $COVERAGE_JULIA_VERSION ]; then
        julia -e 'import Pkg; Pkg.test("Rocket", coverage=true, julia_args=["--inline=no"])';
    fi

after_success:
  - |
    if [ $TRAVIS_JULIA_VERSION == $COVERAGE_JULIA_VERSION ]; then
      julia -e 'import Pkg; cd(Pkg.dir("Rocket")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    fi
