name = "Rocket"
uuid = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"
authors = ["Dmitri Bagaev <bvdmitri@gmail.com>"]
version = "1.2.5"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
DataStructures = "0.17"
julia = "1"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test", "Coverage", "Documenter"]
